version: "3.8"

services:
  backend:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - 5500:5500
    links:
      - mongo
    environment:
      - MONGOURL=mongodb://mongo/docker-deploy

  mongo:  
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: 


