version: "3.8"

services:
  backend:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - 5500:5500
    external_links:
      - mongo

  mongo:  
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017


